"""Initial tables in pulsedesk schema

Revision ID: f95b9cc87776
Revises: 
Create Date: 2026-09-23 17:52:04.168080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f95b9cc87776'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS pulsedesk")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='pulsedesk'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pulsedesk'
    )
    op.create_index(op.f('ix_pulsedesk_users_email'), 'users', ['email'], unique=True, schema='pulsedesk')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['pulsedesk.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pulsedesk'
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['pulsedesk.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pulsedesk'
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['pulsedesk.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pulsedesk'
    )
    op.create_index(op.f('ix_pulsedesk_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True, schema='pulsedesk')
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['pulsedesk.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['pulsedesk.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='pulsedesk'
    )
    op.create_table('ticket_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['pulsedesk.users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['pulsedesk.users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['pulsedesk.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pulsedesk'
    )
    op.create_table('ticket_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['pulsedesk.tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['pulsedesk.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pulsedesk'
    )
    op.create_table('ticket_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('old_status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['pulsedesk.users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['pulsedesk.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pulsedesk'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_status_history', schema='pulsedesk')
    op.drop_table('ticket_comments', schema='pulsedesk')
    op.drop_table('ticket_assignments', schema='pulsedesk')
    op.drop_table('user_roles', schema='pulsedesk')
    op.drop_index(op.f('ix_pulsedesk_tickets_ticket_number'), table_name='tickets', schema='pulsedesk')
    op.drop_table('tickets', schema='pulsedesk')
    op.drop_table('permissions', schema='pulsedesk')
    op.drop_table('audit_logs', schema='pulsedesk')
    op.drop_index(op.f('ix_pulsedesk_users_email'), table_name='users', schema='pulsedesk')
    op.drop_table('users', schema='pulsedesk')
    op.drop_table('roles', schema='pulsedesk')
    op.execute("DROP SCHEMA IF EXISTS pulsedesk CASCADE")
    # ### end Alembic commands ###
